- name: Provision with Ansible
  hosts: all
  user: ubuntu 
  become: true
  
  tasks:
     - name: install nginx
       apt: name=nginx state=present

     - template:
        src: nginx/default.conf
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: 0644



